version: "3.9"

services:
  gta-back:
    build: back/Backend.Api/
    image: gta-back-canary
    ports:
      - "31000:5000"
    restart: unless-stopped

  gta-front:
    build: front/
    image: gta-front-canary
    ports:
      - "30000:5000"
    restart: unless-stopped
