version: "3.9"

services:
  gta-back:
    build: back/Backend.Api/
    image: gta-back-canary
    ports:
      - "31000:5000"
    restart: unless-stopped

  gta-front:
    build: front/
    image: gta-front-canary
    ports:
      - "30000:5000"
    restart: unless-stopped

  gta-db:
    image: postgres
    ports:
      - "61001:5432"
    env_file:
      - .env.postgres
    volumes:
      - ./DATA:/var/lib/postgresql/data
    restart: unless-stopped
