version: "3.9"

services:
  gta-back:
    build: back/Backend.Api/
    image: gta-back-prod
    ports:
      - "11000:5000"
    restart: unless-stopped

  gta-front:
    build: front/
    image: gta-front-prod
    ports:
      - "10000:5000"
    restart: unless-stopped

  gta-db:
    image: postgres
    ports:
      - "61000:5432"
    env_file:
      - .env.postgres
    volumes:
      - ./DATA:/var/lib/postgresql/data
    restart: unless-stopped
