version: "3.9"

services:
  gta-back:
    build: back/Backend.Api/
    image: gta-back-prod
    ports:
      - "11000:5000"
    restart: unless-stopped

  gta-front:
    build: front/
    image: gta-front-prod
    ports:
      - "10000:5000"
    restart: unless-stopped
