// MOVE CAR
export const MOVE_CAR_IS_MOVING = "IS_MOVING";
export const MOVE_CAR_FORCE_IS_MOVING = "FORCE_IS_MOVING";
export const MOVE_CAR_SET_GARAGES = "MOVE_CAR_SET_GARAGES";
export const MOVE_CAR_CHECK_MOVE_LIST = "CHECK_MOVE_LIST";
export const MOVE_CAR_CLEAR_MOVE_LIST = "CLEAR_MOVE_LIST";
export const MOVE_CAR_SET_GARAGE_INPUT = "MOVE_CAR_SET_GARAGE_INPUT";
export const MOVE_CAR_CHECK_CHOSEN_GARAGE = "MOVE_CAR_CHECK_CHOSEN_GARAGE";
export const MOVE_CAR_CLEAR = "MOVE_CAR_CLEAR";
export const MOVE_CAR_CHECK_ERROR_CAR = "MOVE_CAR_CHECK_ERROR_CAR";

// MOVE CAR API
export const MOVE_CAR_API_LOADING = "MOVE_CAR_API_LOADING";
export const MOVE_CAR_API_FAILURE = "MOVE_CAR_API_FAILURE";
export const MOVE_CAR_API_SUCCESS = "MOVE_CAR_API_SUCCESS";

// SEARCH
export const SEARCH_SET_CARS = "SET_SEARCH_CARS";
export const SEARCH_SET_GARAGES = "SET_SEARCH_GARAGES";
export const SEARCH_SET_INPUT = "SEARCH_SET_INPUT";
export const SET_NO_RESULTS = "SET_NO_RESULTS";

// NEWCAR
export const NEWCAR_SET_CAR_NAME = "NEWCAR_SET_CAR_NAME";
export const NEWCAR_SET_GARAGE_NAME = "NEWCAR_SET_GARAGE_NAME";
export const NEWCAR_CHECK_CHOSEN_GARAGE = "NEWCAR_CHECK_CHOSEN_GARAGE";
export const NEWCAR_SET_POSSIBLE_CARS = "NEWCAR_SET_POSSIBLE_CARS";
export const NEWCAR_SET_GARAGES = "NEWCAR_SET_GARAGES";
export const NEWCAR_CLEAR_ALL = "NEWCAR_CLEAR_ALL";
export const NEWCAR_CHECK_CHOSEN_POSSIBLE_CAR =
  "NEWCAR_CHECK_CHOSEN_POSSIBLE_CAR";

// NEWCAR API
export const NEWCAR_API_LOADING = "NEWCAR_API_LOADING";
export const NEWCAR_API_FAILURE = "NEWCAR_API_FAILURE";
export const NEWCAR_API_SUCCESS = "NEWCAR_API_FAILURE";

// NEW GARAGE
export const NEW_GARAGE_SET_NAME = "NEW_GARAGE_SET_NAME";
export const NEW_GARAGE_SET_DESC = "NEW_GARAGE_SET_DESC";

// NEW GARAGE API
export const NEW_GARAGE_API_LOADING = "NEW_GARAGE_API_LOADING";
export const NEW_GARAGE_API_SUCCESS = "NEW_GARAGE_API_SUCCESS";
export const NEW_GARAGE_API_FAILURE = "NEW_GARAGE_API_FAILURE";

// GARAGE MODIFY
export const GARAGEMODIFY_SET_NEW_DESC = "GARAGEMODIFY_SET_NEW_DESC";
export const GARAGEMODIFY_SET_OPEN_GARAGE = "GARAGEMODIFY_SET_OPEN_GARAGE";
export const GARAGEMODIFY_SET_RENAME_BTN_DISABLED =
  "GARAGEMODIFY_SET_RENAME_BTN_DISABLED";
export const GARAGEMODIFY_API_LOADING = "GARAGEMODIFY_API_LOADING";
export const GARAGEMODIFY_API_SUCCESS = "GARAGEMODIFY_API_SUCCESS";
export const GARAGEMODIFY_API_FAILURE = "GARAGEMODIFY_API_FAILURE";
export const GARAGEMODIFY_SET_DELETING_GARAGE =
  "GARAGEMODIFY_SET_DELETING_GARAGE";

// AUTH
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const AUTH_API_STATUS = "AUTH_API_STATUS";

// CAR
export const SET_CAR_BEING_DELETED = "SET_CAR_BEING_DELETED";
