// MOVING
export const IS_MOVING = "IS_MOVING";
export const FORCE_IS_MOVING = "FORCE_IS_MOVING";

export const NEW_GARAGE_ID = "NEW_GARAGE_ID";

export const CHECK_MOVE_LIST = "CHECK_MOVE_LIST";
export const CLEAR_MOVE_LIST = "CLEAR_MOVE_LIST";

// SEARCHING

export const SEARCH_SET_CARS = "SET_SEARCH_CARS";
export const SEARCH_SET_GARAGES = "SET_SEARCH_GARAGES";
export const SEARCH_SET_INPUT = "SEARCH_SET_INPUT";

// NEW CAR
export const NEWCAR_SET_CAR_NAME = "NEWCAR_SET_CAR_NAME";
export const NEWCAR_SET_GARAGE_NAME = "NEWCAR_SET_GARAGE_NAME";
export const NEWCAR_SET_GARAGE_ID = "NEWCAR_SET_GARAGE_ID";

export const NEWCAR_SET_POSSIBLE_CARS = "NEWCAR_SET_POSSIBLE_CARS";
export const NEWCAR_SET_GARAGES = "NEWCAR_SET_GARAGES";

// export const NEWCAR_BAD_GARAGE = "NEWCAR_BAD_GARAGE";
// export const NEWCAR_BAD_CAR = "NEWCAR_BAD_CAR";

// NEW GARAGE
export const NEW_GARAGE_SET_NAME = "NEW_GARAGE_SET_NAME";
export const NEW_GARAGE_SET_DESC = "NEW_GARAGE_SET_DESC";

// AUTH
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_LOGGED_IN = "SET_LOGGED_IN";

export const GARAGE_PAGE = "GARAGE_PAGE";
export const GARAGE_PAGE_CLEAR = "GARAGE_PAGE_CLEAR";
export const GARAGE_PAGE_SET_NAME = "GARAGE_PAGE_SET_NAME";
export const GARAGE_PAGE_SET_DESC = "GARAGE_PAGE_SET_DESC";
