export const MOVE_CAR_IS_MOVING = "IS_MOVING";
export const MOVE_CAR_FORCE_IS_MOVING = "FORCE_IS_MOVING";
export const MOVE_CAR_SET_GARAGES = "MOVE_CAR_SET_GARAGES";
export const MOVE_CAR_CHECK_MOVE_LIST = "CHECK_MOVE_LIST";
export const MOVE_CAR_CLEAR_MOVE_LIST = "CLEAR_MOVE_LIST";
export const MOVE_CAR_SET_GARAGE_INPUT = "MOVE_CAR_SET_GARAGE_INPUT";
export const MOVE_CAR_CHECK_CHOSEN_GARAGE = "MOVE_CAR_CHECK_CHOSEN_GARAGE";
export const MOVE_CAR_CLEAR = "MOVE_CAR_CLEAR";

export const SEARCH_SET_CARS = "SET_SEARCH_CARS";
export const SEARCH_SET_GARAGES = "SET_SEARCH_GARAGES";
export const SEARCH_SET_INPUT = "SEARCH_SET_INPUT";

export const NEWCAR_SET_CAR_NAME = "NEWCAR_SET_CAR_NAME";
export const NEWCAR_SET_GARAGE_NAME = "NEWCAR_SET_GARAGE_NAME";
export const NEWCAR_CHECK_CHOSEN_GARAGE = "NEWCAR_CHECK_CHOSEN_GARAGE";
export const NEWCAR_SET_POSSIBLE_CARS = "NEWCAR_SET_POSSIBLE_CARS";
export const NEWCAR_SET_GARAGES = "NEWCAR_SET_GARAGES";
export const NEWCAR_CLEAR_ALL = "NEWCAR_CLEAR_ALL";
export const NEWCAR_CHECK_CHOSEN_POSSIBLE_CAR =
  "NEWCAR_CHECK_CHOSEN_POSSIBLE_CAR";

export const NEW_GARAGE_SET_NAME = "NEW_GARAGE_SET_NAME";
export const NEW_GARAGE_SET_DESC = "NEW_GARAGE_SET_DESC";

export const GARAGE_PAGE = "GARAGE_PAGE";
export const GARAGE_PAGE_CLEAR = "GARAGE_PAGE_CLEAR";
export const GARAGE_PAGE_SET_NAME = "GARAGE_PAGE_SET_NAME";
export const GARAGE_PAGE_SET_DESC = "GARAGE_PAGE_SET_DESC";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
